- name: create 'ingress-nginx' namespace
  kubernetes.core.k8s:
    name: nginx
    api_version: v1
    kind: Namespace
    state: present

- name: add nginx-stable helm repo
  kubernetes.core.helm_repository:
    name: nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: install nginx
  # https://github.com/kubernetes/ingress-nginx/blob/3476232f5c38383dd157ddaff3b4c7cebd57284e/charts/ingress-nginx/values.yaml
  kubernetes.core.helm:
    name: nginx
    namespace: nginx
    chart_ref: "nginx-stable/nginx-ingress"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes
    values:
      controller:
        ingressClassResource:
          name: nginx
          enabled: true
          default: true
          controllerValue: "k8s.io/ingress-nginx"
        ingressClass: nginx
        watchIngressWithoutClass: true

        kind: deployment

        hostPort:
          enabled: true
          ports:
            http: 80
            https: 443

        service:
          enabled: true
          enableHttp: true
          enableHttps: true
          # ipFamilies:
          #   - IPv4
          loadBalancerIP: "{{ nginx.load_balancer_ip }}"
          ports:
            http: 80
            https: 443
          targetPorts:
            http: http
            https: https
          type: LoadBalancer

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true

        serviceAccount:
          create: true

        admissionWebhooks:
          enabled: false
