# https://artifacthub.io/packages/helm/sonarqube/sonarqube#elasticsearch-prerequisites
# https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html#vm-max-map-count
- name: configure sonarqube prerequisites
  shell: |
    sysctl -w vm.max_map_count=262144
