# oauth2-proxy and keycloak are all in the same namespace
- name: create 'oauth' namespace
  kubernetes.core.k8s:
    name: oauth
    api_version: v1
    kind: Namespace
    state: present

# Bitnami has a helm chart for Keycloak, but try this first
# https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/20.0.2/kubernetes-examples/keycloak.yaml
- name: declare Keycloak as a Service
  kubernetes.core.k8s:
    state: present
    namespace: oauth
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: keycloak
        labels:
          app: keycloak
      spec:
        ports:
          - name: http
            port: 8080
            targetPort: 8080
        selector:
          app: keycloak
        loadBalancerIP: "{{ keycloak.load_balancer_ip }}" # for debugging
        type: LoadBalancer

# TODO - remove some hard coded arguments
- name: transfer Keycloak config file from Ansible development machine to helm host
  delegate_to: localhost
  shell: |
    rsync /home/ansible/homelab/homelab-services-ansible/roles/keycloak/config/homelab-users-realm.json ansible@192.168.20.119:~

- name: deploy Keycloak
  kubernetes.core.k8s:
    state: present
    namespace: oauth
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak
        labels:
          app: keycloak
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: keycloak
        template:
          metadata:
            labels:
              app: keycloak
          spec:
            containers:
              - name: keycloak
                image: quay.io/keycloak/keycloak:20.0.2
                # https://www.mastertheboss.com/keycloak/keycloak-with-docker/
                args: ["start-dev --import-realm"]
                env:
                  - name: KEYCLOAK_ADMIN
                    value: "admin"
                  - name: KEYCLOAK_ADMIN_PASSWORD
                    value: "admin"
                  - name: KC_PROXY
                    value: "edge"
                # https://www.keycloak.org/server/importExport
                # https://kubernetes.io/docs/concepts/storage/volumes/
                volumeMounts:
                  - name: keycloak-init-config
                    mountPath: /opt/keycloak/data/import
                ports:
                  - name: http
                    containerPort: 8080
                readinessProbe:
                  httpGet:
                    path: /realms/master
                    port: 8080
            # https://kubernetes.io/docs/concepts/storage/volumes/
            volumes:
              - name: keycloak-init-config
                hostPath:
                  path: /home/ansible/homelab-users-realm.json
                  type: File

- name: define a VirtualService for Keycloak
  kubernetes.core.k8s:
    name: virtualservice-keycloak
    state: present
    namespace: oauth
    definition:
      apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: keycloak
        namespace: oauth
      spec:
        gateways:
          - shared-gateway.istio-system.svc.cluster.localv # master gateway (there probably should only be 1 gateway) 
        hosts:
          - "{{ keycloak.keycloak_dn }}"
        http:
          - match:
              - uri:
                  prefix: /
              - uri:
                  regex: '^.*\.(ico|png|jpg|js|woff|svg|woff2|eot|ttf|css)$'
            route:
              - destination:
                  host: keycloak.oauth.svc.cluster.local
                  port:
                    number: 8080 # this matches the port set above fpr the Deployment
