- name: create 'sonarqube' namespace
  kubernetes.core.k8s:
    name: sonarqube
    api_version: v1
    kind: Namespace
    state: present
    definition:
      metadata:
        labels:
          istio-injection: enabled # https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/


        
- name: define a VirtualService for Sonarqube
  kubernetes.core.k8s:
    name: virtualservice-sonarqube
    state: present
    namespace: sonarqube
    definition:
      apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: sonarqube
        namespace: sonarqube
      spec:
        gateways:
          # https://discuss.istio.io/t/istio-ingressgateway-controller-and-namespaces/1217/8
          - shared-gateway.istio-system.svc.cluster.local
        hosts:
          - "sonarqube.milkyway.localhostcert.net"
        # https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute
        http:
          # https://github.com/istio/istio/issues/19599
          - name: "sonarqube routes"
            match:
              - uri:
                  prefix: /
              - uri:
                  regex: '^.*\.(ico|png|jpg|js|woff|svg|woff2|eot|ttf|css)$'
            route:
              - destination:
                  # use 'kubectl run alpine --rm -ti --image alpine /bin/sh' to debug from within cluster
                  host: gitea-http.gitea.svc.cluster.local
                  port:
                    number: 9000 # this matches the port defined in the helm chart

                  # https://medium.com/@in.live.in/puzzling-503s-and-istio-1bf504b9aae6
                  # this appears needed to work around HTTP 503 errors
                  retries:
                    attempts: 3
                    perTryTimeout: 5s
                    retryOn: gateway-error,connect-failure,refused-stream
