##################################################
#
# Istio base (https://artifacthub.io/packages/helm/istio-official/base)
#

- name: create 'istio-system' namespace
  kubernetes.core.k8s:
    name: istio-system
    api_version: v1
    kind: Namespace
    state: present

- name: add 'istio-base' helm repo
  kubernetes.core.helm_repository:
    name: istio-base
    repo_url: https://istio-release.storage.googleapis.com/charts

- name: install 'istio-base'
  kubernetes.core.helm:
    name: istio-base
    namespace: istio-system
    chart_ref: "istio/base"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes

##################################################
#
# Istiod (https://artifacthub.io/packages/helm/istio-official/istiod)
#

- name: install 'istiod'
  kubernetes.core.helm:
    name: istiod
    namespace: istio-system
    chart_ref: "istio/istiod"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes

##################################################
#
# Istio Gateway (https://artifacthub.io/packages/helm/istio-official/gateway)
#

- name: install 'istio-ingressgateway'
  kubernetes.core.helm:
    name: istio-ingressgateway
    namespace: istio-system
    chart_ref: "istio/gateway"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes
    values:
      service:
        type: LoadBalancer
        ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
        loadBalancerIP: "{{ istio.load_balancer_ip }}"

# ##################################################
# #
# # Istio install the actual gateway (https://github.com/datastrophic/kubernetes-deployment)
# #

- name: install a shared-gateway to be reused by other deployments
  kubernetes.core.k8s:
    name: shared-gateway
    state: present
    namespace: istio-system
    definition:
      apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: shared-gateway
        namespace: istio-system
      spec:
        selector:
          # Use the default Ingress Gateway installed by Istio
          istio: ingressgateway
        servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
          - "*"
          # - "gitea.andromeda.lab"
          # - "jenkins.andromeda.lab"
          
