- name: create jenkins namespace
  kubernetes.core.k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present

- name: create secret
  kubernetes.core.k8s:
    state: present
    namespace: jenkins
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: jenkins-secret
      data:
        jenkins-admin-password: "{{ jenkins.admin_password | b64encode }}"
        jenkins-admin-user: YWRtaW4=
      type: Opaque

- name: create secret text (cicd jenkins token)
  kubernetes.core.k8s:
    state: present
    namespace: jenkins
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ns-cicd-sa-jenkins-token
        labels:
          "jenkins.io/credentials-type": "secretText"
        annotations:
          "jenkins.io/credentials-description" : "jenkins service account token (ns: cicd)"
      stringData:
        text: "{{ jenkins_token }}"
      type: Opaque

- name: add jenkins helm repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: purge jenkins
  kubernetes.core.helm:
    name: jenkins
    namespace: jenkins
    state: absent
    wait: true

- name: install jenkins
  kubernetes.core.helm:
    name: jenkins
    namespace: jenkins
    chart_ref: jenkins/jenkins
    create_namespace: true
    purge: yes
    update_repo_cache: yes
    values:
      controller:
        adminSecret: true
        jenkinsUrl: http://192.168.2.241
        #jenkinsUrlProtocol:
        #jenkinsUriPrefix: /
        serviceType: LoadBalancer
        servicePort: 80
        admin:
          existingSecret: jenkins-secret
        installPlugins:
          - kubernetes:3670.v6ca_059233222  # https://plugins.jenkins.io/kubernetes/
          - workflow-aggregator:590.v6a_d052e5a_a_b_5  # https://plugins.jenkins.io/workflow-aggregator/
          - git:4.11.4  # https://plugins.jenkins.io/git/
          - configuration-as-code:1512.vb_79d418d5fc8  # https://plugins.jenkins.io/configuration-as-code/
          - kubernetes-credentials-provider:1.196.va_55f5e31e3c2  # https://plugins.jenkins.io/kubernetes-credentials-provider/
          - job-dsl:1.81  # https://plugins.jenkins.io/job-dsl/
          - ldap:2.11  # https://plugins.jenkins.io/ldap/
          - role-strategy:555.v8d194cc85b_30  # https://plugins.jenkins.io/role-strategy/
        JCasC:
          configScripts:
            jenkins-casc-configs: |
              jenkins:
                systemMessage: Labs - Get going
                clouds:
                  - kubernetes:
                      containerCap: 10
                      containerCapStr: "10"
                      credentialsId: "ns-cicd-sa-jenkins-token"
                      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:80"
                      name: "cicd"
                      namespace: "cicd"
                      serverUrl: "https://kubernetes.default"
              jobs:
                - script: >
                    pipelineJob('go-sample') {
                      description("go-sample pipeline")
                      definition {
                        cpsScm {
                          scm {
                            git {
                              remote { url('https://github.com/markperdue/go-sample.git') }
                              branches('master')
                              scriptPath('Jenkinsfile')
                              extensions { }
                              lightweight(true)
                            }
                          }
                        }
                      }
                    }
      persistence:
        enabled: true
        storageClass: longhorn
      rbac:
        readSecrets: true
