- name: add metallb helm repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: install metallb
  kubernetes.core.helm:
    name: metallb
    namespace: metallb-system
    chart_ref: metallb/metallb
    create_namespace: true
    wait: yes

- name: configure metallb address pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - 192.168.2.240-192.168.2.250

- name: configure metallb l2 advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: first-pool
        namespace: metallb-system
