- name: create 'traefik' namespace
  kubernetes.core.k8s:
    name: traefik
    api_version: v1
    kind: Namespace
    state: present

- name: add traefik helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: install traefik
  kubernetes.core.helm:
    name: traefik
    namespace: traefik
    chart_ref: "traefik/traefik"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes
    values:
      # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml?ref=traefik.io
      # api:
      #   dashboard: true
      #   debug: true
      #   # insecure: true

      globalArguments:
        - "--global.sendanonymoususage=false"
        - "--global.checknewversion=false"

      additionalArguments:
        - "--serversTransport.insecureSkipVerify=true"
        - "--log.level=DEBUG"

      deployment:
        enabled: true
        replicas: 3
        annotations: {}
        podAnnotations: {}
        additionalContainers: []
        initContainers: []

      ports:
        web:
          redirectTo: websecure
        websecure:
          tls:
            enabled: true
            
      ingressRoute:
        dashboard:
          enabled: false

      providers:
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-external
          allowExternalNameServices: true
          # https://doc.traefik.io/traefik/v2.10/providers/kubernetes-crd/#allowcrossnamespace
          allowCrossNamespace: true
        kubernetesIngress:
          enabled: true
          allowExternalNameServices: true
          publishedService:
            enabled: false

      rbac:
        enabled: true

      service:
        enabled: true
        type: LoadBalancer
        annotations: {}
        labels: {}
        spec:
          loadBalancerIP: "{{ traefik.load_balancer_ip }}"
        loadBalancerSourceRanges: []
        externalIPs: []

      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 128Mi

# - name: configure traefik
#   kubernetes.core.k8s:
#     state: present
#     definition:
#       apiVersion: traefik.containo.us/v1alpha1
#       kind: Middleware
#       metadata:
#         name: default-headers
#         namespace: traefik
#       spec:
#         headers:
#           browserXssFilter: true
#           contentTypeNosniff: true
#           forceSTSHeader: true
#           stsIncludeSubdomains: true
#           stsPreload: true
#           stsSeconds: 15552000
#           customFrameOptionsValue: SAMEORIGIN
#           customRequestHeaders:
#             X-Forwarded-Proto: https
