- name: create 'openldap' namespace
  kubernetes.core.k8s:
    name: openldap
    api_version: v1
    kind: Namespace
    state: present

# - name: create openldap secrets
#   kubernetes.core.k8s:
#     state: present
#     namespace: openldap
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: openldap-secrets
#       data:
#         adminusername: "{{ openldap.ldap_admin_username }}"
#         adminpassword: "{{ openldap.ldap_admin_password }}"
#         users: "{{ openldap.ldap_users }}"
#         passwords: "{{ openldap.ldap_user_passwords }}"
#       type: Opaque

- name: clear openldap secrets
  ansible.builtin.command:
    cmd: |-
      kubectl delete secret openldap --namespace="openldap" --ignore-not-found

- name: create openldap secrets
  ansible.builtin.command:
    cmd: |-
      kubectl create secret generic openldap
      --namespace="openldap"
      --from-literal=adminusername="{{ openldap.ldap_admin_username }}"
      --from-literal=adminpassword="{{ openldap.ldap_admin_password }}" 
      --from-literal=users="{{ openldap.ldap_users }}"
      --from-literal=passwords="{{ openldap.ldap_user_passwords }}"

- name: openldap deployment
  kubernetes.core.k8s:
    name: openldap
    state: present
    namespace: openldap
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: openldap
        labels:
          app.kubernetes.io/name: openldap
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: openldap
        replicas: 1
        template:
          metadata:
            labels:
              app.kubernetes.io/name: openldap
          spec:
            containers:
              - name: openldap
                image: docker.io/bitnami/openldap:latest
                imagePullPolicy: "Always"
                env:
                  - name: LDAP_ADMIN_USERNAME
                    valueFrom:
                      secretKeyRef:
                        key: adminusername
                        name: openldap
                  - name: LDAP_ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: adminpassword
                        name: openldap
                  - name: LDAP_USERS
                    valueFrom:
                      secretKeyRef:
                        key: users
                        name: openldap
                  - name: LDAP_PASSWORDS
                    valueFrom:
                      secretKeyRef:
                        key: passwords
                        name: openldap
                ports:
                  - name: tcp-ldap
                    containerPort: 1389

- name: start openldap service
  kubernetes.core.k8s:
    name: openldap
    state: present
    namespace: openldap
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: openldap
        labels:
          app.kubernetes.io/name: openldap
      # spec:
      #   type: LoadBalancer
      #   loadBalancerIP: "{{ openldap.load_balancer_ip }}"
      #   ports:
      #     - name: tcp-ldap
      #       port: 1389
      #       targetPort: tcp-ldap
      #   selector:
      #     app.kubernetes.io/name: openldap
      spec:
        type: ClusterIP
        ports:
          - name: tcp-ldap
            port: 1389
            targetPort: tcp-ldap
        selector:
          app.kubernetes.io/name: openldap
