- hosts: localhost
  gather_facts: no
  module_defaults:
    ansibleguy.opnsense.wireguard_general:
        firewall: '192.168.10.1'
        api_credential_file: '/home/ansible/.secret/router.andromeda_apikey.txt'
        ssl_verify: false
        debug: true

  tasks:
    - name: Enabling WireGuard service
      ansibleguy.opnsense.wireguard_general:
        enabled: true
