- name: create 'certmanager' namespace
  kubernetes.core.k8s:
    name: certmanager
    api_version: v1
    kind: Namespace
    state: present

- name: add certmanager helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: install certmanager
  kubernetes.core.helm:
    name: certmanager
    namespace: certmanager
    chart_ref: "jetstack/cert-manager"
    create_namespace: false
    # purge: yes
    update_repo_cache: yes
    values:
      # https://github.com/cert-manager/cert-manager/issues/2956\
      # need to clear out old CRDs before putting in new ones
      # kubectl get crd --all-namespaces | grep cert
      # kubectl delete crd <results from above>
      installCRDs: true
