####################################################
# General configurations
####################################################

tld: "{{ vault_domain_name }}"
third_level_domain: "{{ vault_third_level_domain }}"
lan_tld: "{{ third_level_domain }}.{{ domain_name }}"

####################################################
# Firewall configurations
####################################################

# firewall information
firewall_hostname: "{{ vault_firewall_hostname }}" 
# on host launching Ansible
firewall_credential_file: "{{ vault_firewall_credential_file }}" 

####################################################
# MetalLB configurations
####################################################

# IP addresses to provide internal to this cluster 
# (these must be considered as static IPs to the router)
metallb:
  address_pool: "{{ vault_metallb_address_pool }}"

####################################################
# Kubernetes dashboard configurations
####################################################

kubernetes_dashboard:
  load_balancer_ip: "{{ vault_kubernetes_dashboard_load_balancer_ip }}"
  hostname: "kubedash"
  manifest_url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml

####################################################
# Longhorn configurations
####################################################

longhorn:
  load_balancer_ip: "{{ vault_longhorn_load_balancer_ip }}"
  hostname: "longhorn"

####################################################
# Metrics server configurations
####################################################

metrics_server:
  enabled: true

####################################################
# PiHole configurations
####################################################

pihole:
  admin_password: "{{ vault_pihole_admin_password }}"
  home_dns: "{{ vault_pihole_network_dns_ip }}"
  dns_load_balancer_ip: "{{ vault_pihole_dns_load_balancer_ip }}"
  hostname: "pihole"
  time_zone: "{{ vault_pihole_time_zone }}"

####################################################
# Gitea configurations
####################################################

gitea:
  admin_user: "{{ vault_gitea_admin_user }}"
  admin_password: "{{ vault_gitea_admin_password }}"
  hostname: "gitea"
  gitea_dn: "gitea.{{ third_level_domain }}.{{ domain_name }}"
  ssh_load_balancer_ip: "{{ vault_gitea_ssh_load_balancer_ip }}"
  ssh_hostname: "gitea-ssh"

####################################################
# Istio configurations
####################################################

# the gateway should be able to handle all traffic in an HTTPS way, 
# and the Istio Gateway itself needs an IP
istio:
  load_balancer_ip: "{{ vault_istio_load_balancer_ip }}"
  cert_manager_credential_file: "{{ vault_istio_cert_manager_credential_file }}"

####################################################
# Keycloak configurations
####################################################

keycloak:
  hostname: "auth"
  keycloak_dn: "auth.{{ third_level_domain }}.{{ domain_name }}"

  # Gitea Keycloak OIDC
  gitea_oidc_secret: "{{ vault_keycloak_gitea_oidc_secret }}"
  gitea_client_id: "{{ vault_keycloak_gitea_client_id }}"
